m

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -10,3 +10,10 @@ echo "Hello World!" > /usr/share/nginx/html/index.html
 # Restart nginx without using systemctl
 service nginx restart
 
+# Check if nginx restarted successfully
+if [ $? -eq 0 ]; then
+    echo "Nginx restarted successfully"
+else
+    echo "Failed to restart nginx"
+fi
+
